name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: terraform-provider-gandi-linux_amd64
          - os: macos-latest
            asset_name: terraform-provider-gandi-darwin_amd64
          - os: windows-latest
            asset_name: terraform-provider-gandi-windows_amd64
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        make cibuild

    - name: Format
      uses: sjkaliski/go-github-actions/fmt@v1.0.0
      if: runner.os == 'Linux'
      env:
        GO_IGNORE_DIRS: "./vendor"

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      if: runner.os == 'Linux'
      with:
        working-directory: "./gandi/"
        skip-pkg-cache: true

# This still does something weird, comment out for now
#    - name: TF Provider Lint
#      uses: bflad/tfproviderlint-github-action@master
#      if: runner.os == 'Linux'
#      with:
#        args: "./..."

    - uses: actions/upload-artifact@v2
      name: Upload
      with:
        name: build-artifact
        path: ${{ matrix.asset_name }}
